# Flutter Web CI Workflow

name: Flutter Web CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Flutter SDK
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"
          channel: stable

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Analyze code (won’t fail build if only warnings)
      - name: Analyze project source
        run: flutter analyze || true

      # Build Flutter Web
      - name: Build Web
        run: flutter build web --release

      # Upload Web build as artifact
      - name: Upload Web Build
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web-build
          path: build/web

